[project]
name = "pyrsd"
version = "0.0.1"
description = "Rainbow Schlieren Deflectometry processing library"
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "scipy",
    "opencv-python",
    "matplotlib",
]

[project.optional-dependencies]
abel = ["PyAbel"]
denoising = ["scikit-image","bm3d"]
hdf5 = ["h5py"]
dev = ["pytest"]

[build-system]
requires = ["setuptools","wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["pyrsd*"]
